Add driver-service functionality and fix passenger-service
adamonissasha/cab-aggregator-app pull request #2
Opened 2023-11-15 08:23 UTC by adamonissasha

2023-11-15 09:14 UTC, AbandonedScope requested changes

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/CarServiceImpl.java
> +        }
```suggestion
       newCar = carRepository.findCarByNumber(carRequest.getNumber())
             .orElseThrow(() -> new CarNumberUniqueException(CAR_NUMBER_EXIST))) {
       newCar = carRepository.save(newCar);
       return mapCarToCarResponse(newCar);
```

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/CarServiceImpl.java
> +        }
Ты можешь просто сравнить здесь id-шники машин, или через equals, нет необходимости вводить отдельный метод репозитория для этого

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverRatingServiceImpl.java
> +            throw new DriverRatingNotFoundException(DRIVER_RATINGS_NOT_FOUND);
используй `...orElseThrow()`

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverRatingServiceImpl.java
> +            throw new DriverRatingNotFoundException(DRIVER_RATINGS_NOT_FOUND);
используй `...orElseThrow()`

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                    return mapDriverToDriverResponse(newDriver);
Это можно вынести в отдельный метод, чтобы `map `не был раздутым

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                    return mapDriverToDriverResponse(updatedDriver);
Тут тоже вынеси в отдельный метод

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by(sortBy).ascending());
А если поля `sortBy` не существует?

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/resources/application.yml
> +    password:
Передашь через переменные среды?
В любом случае, так лучше не делай, задай какие дефолтные, которые для локальной разработки

2023-11-15 09:14 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/dto/response/PassengerRatingResponse.java
> +    private Integer rating;
Просто интересно, чем вызвано такое решение?

2023-11-15 09:14 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/handler/GlobalExceptionHandler.java
> +    public String handleIllegalArgumentException(IllegalArgumentException ex) {
Возвращай dto

2023-11-15 09:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/controller/DriverRatingController.java
> +    public List<DriverRatingResponse> getRatingsByDriverId(@PathVariable("driverId") long driverId) {
Возвращай dto с полем `List<DriverRatingResponse>`, это будет полез, если мы вдруг захотим добавить какие-нибудь метаданные к ответу(кол-во записей, кол-во записей на странице и т.д)

2023-11-15 09:14 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/service/impl/PassengerRatingServiceImpl.java
> +        } else {
Используй `....orElseThrow()`

2023-11-15 09:14 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/service/impl/PassengerRatingServiceImpl.java
>          else {
Используй `....orElseThrow()`

2023-11-15 09:32 UTC, adamonissasha commented on passenger-service/src/main/java/com/example/passengerservice/dto/response/PassengerRatingResponse.java
> +    private Integer rating;
Прочитала, что для работы с бд всегда лучше использовать классы обертки

2023-11-15 09:34 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/dto/response/PassengerRatingResponse.java
> +    private Integer rating;
Но это dto, которое отправляется пользователю, оно с бд не связано

2023-11-15 12:25 UTC, adamonissasha commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverRatingServiceImpl.java
> +            throw new DriverRatingNotFoundException(DRIVER_RATINGS_NOT_FOUND);
Как ее применить, если здесь список List<PriverRating>?

2023-11-15 12:58 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverRatingServiceImpl.java
> +            throw new DriverRatingNotFoundException(DRIVER_RATINGS_NOT_FOUND);
Да, извини, не обратил внимание. Но в любом случае, странно выбрасывать исключение, если список пустой. Просто и возвращала бы его пустым

2023-11-15 19:04 UTC, AbandonedScope requested changes

2023-11-15 19:04 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/controller/DriverController.java
> +        return driverService.editDriver(id, driverRequest);
Сам метод тоже переименуй

2023-11-15 19:04 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        driverRepository.findDriverByPhoneNumberAndIdIsNot(driverRequest.getPhoneNumber(), id)
Не думаю, что эта строка правильна

2023-11-15 19:06 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by(sortBy).ascending());
@adamonissasha

2023-11-16 14:49 UTC, AbandonedScope requested changes

2023-11-16 14:49 UTC, AbandonedScope commented on driver-service/src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                Arrays.asList(FIELD_ID, FIELD_FIRST_NAME, FIELD_LAST_NAME, FIELD_PHONE_NUMBER, FIELD_EMAIL, FIELD_CAR_ID);
Эти поля можно получить через рекурсию

2023-11-16 14:49 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/service/impl/PassengerRatingServiceImpl.java
>              throw new PassengerRatingNotFoundException(PASSENGER_RATINGS_NOT_FOUND);
```suggestion
        if (passengerRatings.isEmpty()) {
            throw new PassengerRatingNotFoundException(PASSENGER_RATINGS_NOT_FOUND);
         }
```

2023-11-16 14:49 UTC, AbandonedScope commented on passenger-service/src/main/java/com/example/passengerservice/service/impl/PassengerRatingServiceImpl.java
> +        passengerRepository.findById(passengerId)
findById лучше не использовать для этих целей, создай в репозитории метод existsById

2023-11-16 17:23 UTC, AbandonedScope approved these changes

2023-11-16 20:16 UTC, merged