Add ride-service functionality
adamonissasha/cab-aggregator-app pull request #3
Opened 2023-11-21 15:20 UTC by adamonissasha

2023-11-22 09:22 UTC, AbandonedScope requested changes

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/model/PromoCode.java
> +import lombok.*;
Do not use ster import

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/model/Ride.java
> +    private Double price;
It is better to use `Decimal` with prices

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/model/PromoCode.java
> +    private String name;
I'm not sure if the promo code can be said to have a `name`. Maybe the `code` is  more appropriate

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/service/impl/PromoCodeServiceImpl.java
> +        }
`optionalPromoCode.get().getEndDate().isAfter(startDate)` - i dont think we should throw `PromoCodeAlreadyExistsException(PROMO_CODE_ALREADY_EXISTS)` in this case.
Move it into the if statement above

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/service/impl/PromoCodeServiceImpl.java
> +                && optionalPromoCode.get().getEndDate().isAfter(startDate)) {
`optionalPromoCode.get().getEndDate().isAfter(startDate)` -  the same

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/service/impl/PromoCodeServiceImpl.java
> +        }
?

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/service/impl/RideServiceImpl.java
> +        }
Why not to check if ride is started the same way as above?

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/service/impl/RideServiceImpl.java
> +        checkRideStatusNotEquals(ride, RideStatus.STARTED, RIDE_STARTED);
Think about the way you can do in in one method call

2023-11-22 09:22 UTC, AbandonedScope commented on rides-service/src/main/resources/db/changelog/changeset/create-ride-table.yaml
> +                  type: bigint
Why don't you use `bigserial`?

2023-11-22 21:33 UTC, adamonissasha commented on rides-service/src/main/java/com/example/ridesservice/dto/response/RideResponse.java
> +    private List<StopResponse> stops;
Я рассчитывала, что в список остановок входят только промежуточные остановки, то есть если их нет, вообще не использовать stopService

2023-11-22 21:40 UTC, adamonissasha commented on rides-service/src/main/java/com/example/ridesservice/service/impl/PromoCodeServiceImpl.java
> +        }
Но здесь идет проверка именно на наличие промокода с таким же именем в тот же период, и если периоды действия промокодов пересекаются, значит такой уже существует, а в предыдущем операторе if проверяется на то, не указана ли дата окончания раньше даты начала или раньше сегодняшнего дня

2023-11-22 21:47 UTC, adamonissasha commented on rides-service/src/main/java/com/example/ridesservice/service/impl/RideServiceImpl.java
> +        }
в checkRideStatusNotEquals исключение выбрасывается если статус совпадает, а в этом случае наоборот, если статус не равен STARTED

2023-11-22 22:02 UTC, adamonissasha commented on rides-service/src/main/java/com/example/ridesservice/service/impl/RideServiceImpl.java
> +        }
я все же сделала отдельный метод для этой проверки, так как дважды используется, неправильно поняла сначала

2023-11-23 15:59 UTC, AbandonedScope requested changes

2023-11-23 15:59 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/controller/PromoCodeController.java
> +    public List<PromoCodeResponse> getAllPromoCodes() {
`List<PromoCodeResponse>` -> to dto

2023-11-23 15:59 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/controller/RideController.java
> +    @PostMapping()
`@ResponseStatus`?

2023-11-23 15:59 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/controller/RideController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```

2023-11-23 15:59 UTC, AbandonedScope commented on rides-service/src/main/java/com/example/ridesservice/model/enums/RideStatus.java
> +    private final String message;
What is this message used for? I mean, from the name we cannot fully understand where it is used.

2023-11-23 16:00 UTC, AbandonedScope commented
Ещё один момент - те комментарии, что ты поправила - отмечай как resolved

2023-11-23 22:49 UTC, AbandonedScope approved these changes

2023-11-27 03:50 UTC, merged